# If your yazi version is lower than v25.5.28, repleace "mgr" by "manager".
[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = "plugin goto-projects"
desc = "Go to Projects directory"

[[mgr.prepend_keymap]]
on = [ "M" ]
run = "plugin marktext"
desc = "Open with MarkText"

[[mgr.prepend_keymap]]
on = [ "g", "s" ]
run = "plugin git-pane status"
desc = "Show git status in a new WezTerm pane"

[[mgr.prepend_keymap]]
on = [ "g", "l" ]
run = "plugin git-pane log"
desc = "Show git log in a new WezTerm pane"

[[mgr.prepend_keymap]]
on = [ "g", "L" ]
run = "plugin git-pane log-oneline"
desc = "Show git log --oneline in a new WezTerm pane"

[[mgr.prepend_keymap]]
on = [ "!", "!" ]
run = "plugin shell-pane"
desc = "Open a shell in a new WezTerm pane"

[[mgr.prepend_keymap]]
# on = [ "m" ]
on = [ "b", "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
# on = [ "'" ]
on = [ "b", "g" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"
