[mgr]
show_hidden = true
linemode = "size_and_mtime"

[opener]
edit = [
    { run = "vim %s", desc = "vim", for = "windows", block = true },
    { run = "gvim %s", desc = "gvim", for = "windows", orphan = true },
    { run = "C:\\Progra~1\\Notepad++\\notepad++.exe %s", desc = "notepad++", for = "windows", block = true },
    { run = "vim '%s'", desc = "vim", for = "unix", block = true },
]

[open]
rules = [
    { mime = "*", use = "edit" },
]
